### ISSUE TITLE
angular-froala does not show content before click when initOnClick set to true

### ISSUE THREAD

**Issue by agabhane** [froala/angular-froala#164]
I am using `angular-froala` with angular 1.5.x and came across the below issue.

I am initializing froala with `initOnClick `as `true`.
The problem is, it is not showing content before clicking.
If my variable given to `ng-model` is not empty then it should display the content and not placeholder.
Please find attached [punker](https://embed.plnkr.co/sWt9gy30rwOEulgPnQxS/)

**Example:**
If  `$scope.myHtml = "<p>Some text</p>";`

**Actual:**
Editor displays default placeholder before clicking.

**Expected:**
Editor should display "Some text" before clicking

**Comment by FWennerdahl** [comment]
We're also affected by this issue and it's preventing us from using Froala in production.

Just to make sure that this was an issue in angular-froala we created a jsfiddle using Froala without angular, where the issue is not reproducible: https://jsfiddle.net/a9h6kpy0/

**Comment by FWennerdahl** [comment]
@stefanneculai: The issue is that the `'froalaEditor.initialized'` isn't fired when using `initOnClick: true` until the editor has been clicked. 01bcc7d669eb2e9dc8f1ea2142ce671604762d4b doesn't fix this as `flushNgModel()` still won't be executed until this event has fired.

Also, when it does `ctrl.initialized`will be set to `true` anyway so the added line won't be executed.

Please re-consider #171 as it has taken these things into consideration.

**Comment by FWennerdahl** [comment]
Fix seems to work. Thanks!

**Comment by stefanneculai** [comment]
It should be fixed on the current master. Could you please check?

**Comment by FWennerdahl** [comment]
Yes, I noticed the other changes in e124ecfd2afdde6707dda2aa34990ee0d107ddce after I posted the message. Tested and it's working 👍
