### ISSUE TITLE
"Unlicensed Froala Editor" on local dev machine

### ISSUE THREAD

**Issue by corporationsruleyourmom** [froala/angular-froala#19]
Hey,

I wanted to test out the Froala WYSIWYG editor in my AngularJS v1.3.15 app. I installed via bower and launched my app on the development with a local IP address 192.168.0.X I received the error message "Unlicensed Froala Editor." How can I test this editor to see if it's worth purchasing a license?

Thanks!

**Comment by cgallarno** [comment]
—

**Comment by stefanneculai** [comment]
The Unlicensed message doesn't limit in any way the editor's functionality.

**Comment by corporationsruleyourmom** [comment]
Well, let me re-phrase, the editor did not show up only an "Unlicensed Froala Editor" button could be seen... Anyway to fix this? Or is Froala only accessible via localhost and not local ip addresses. Any help would be, well, helpful! Thanks.

**Comment by Mkey85** [comment]
Any updates here?

**Comment by dbakshi** [comment]
Hi, i used froala editor in my project. It worked fine on my local. Now when i saw it on my live site server, it is throwing this error. "Unlicenced copy of froala editor. Use it legally by purchasing a licence. " How to fix it, as then it should have thrown same error in my local machine. Now that i used it ,invested a lot of time in it. Now after few days checking on server, it is creating issue. Kindly help so that i can use this without actually buying it. Reply asap. Very urgent
Regards
Dharna
