### ISSUE TITLE
TypeError: Object doesn't support property or method 'froalaEditor'

### ISSUE THREAD

**Issue by GregJF** [froala/angular-froala#59]
This error is throw in by "angular-froala.js" at line 36, which is:
       ctrl.froalaEditor = element.froalaEditor(ctrl.options).data('froala.editor').$el;

So how do I setup froala text editor in Angular to stop this error occurring.

**Comment by cgallarno** [comment]
Are you using Froala WYSIWYG Editor Version 2?

**Comment by navneet35371** [comment]
+1

**Comment by pine0510** [comment]
I have same issues.

**Comment by andrewattellwise** [comment]
I did have the same issue. It turned out that I was initializing jquery twice. Once before angular so that angular will use jquery instead of jqLite. And once [by accident] before froala. This caused froala to use the 2nd jquery instance.

You can confirm this by setting a breakpoint before line 36 and observe that angular.element === window.jQuery is false.
If it is false then you've probably set something up wrong. Make sure you load jquery before angular is initialized and that you don't have a re-initialize of jquery.

**Comment by GregJF** [comment]
andrewattellwise, thanks for the heads up

**Comment by stefanneculai** [comment]
Should be fixed on the master.
