### ISSUE TITLE
is there a way to set the sanitizer to allow specific directives ?

### ISSUE THREAD

**Issue by PedroEsperanca** [froala/angular-froala#62]
I would like to allow directives such as ng-click and even some specific custom directives to be used in the froala editor.

**Comment by cgallarno** [comment]
Hello PedroEsperanca, 

We do the same thing in our project and in order to do this we created our own branch of angular-froala and edited the froala-sanitize. On lines 196, and 201 two objects are defined with what's considered an 'allowed' element.

We created a new object with our custom elements and added that to the list of `validElements`.

you can see how we changed `froala-sanitize` here: https://github.com/Dorsata/angular-froala/blob/master/src/froala-sanitize.js#L206
