### ISSUE TITLE
angular-froala 2.1.0 data-binding not working with angular 1.1.5

### ISSUE THREAD

**Issue by MarioJonckers** [froala/angular-froala#73]
Please tak a look at my question on [stackoverflow](http://stackoverflow.com/questions/35267998/angular-froala-2-1-0-data-binding-not-working-with-angular-1-1-5)

**Comment by cgallarno** [comment]
@MarioJonckers This looks to be an issue with angular (https://github.com/angular/angular.js/issues/1924) which should be fixed in 1.2. If updating angular isn't an option there are some workarounds mentioned in that thread. If you can find a way to get angular-froala to work with 1.1.5 pull requests are welcome.

**Comment by MarioJonckers** [comment]
Using $parent on the ngModel AND calling scope.$apply() in the froala-directive fixed the issue for me.
