### ISSUE TITLE
Unable to type in Inonic Cordova App

### ISSUE THREAD

**Issue by abhinavguptas** [froala/angular-froala#8]
Editor is showing well, both inline and explicit via toolbar. But I can't type in,  no JS errors thrown as well.

**Comment by dennisharrison** [comment]
@cgallarno a little more detail here

Editor works fine in Ionic framework on desktop browsers.  Mobile is the problem here.

Android Chrome (latest and beta - as of posting):
Have to press and hold in editor to be able to type text - then it works as intended.

iOS 7.1 & 8.1.3 Safari & Chrome:
Editor will 'focus' as in the event is fired and loggable, keyboard pops up, but no text shows up in the editor window itself.

Also, the editor exhibits the same without the angular wrapper in the Ionic framework.  Just verified.
